# ------------------------
# Global
# ------------------------
namespaceOverride: monitoring

rbac:
  create: true

# ------------------------
# Prometheus
# ------------------------
prometheus:
  enabled: true

  rbac:
    create: true

  prometheusSpec:
    replicas: 1
    retention: 12h
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

# ------------------------
# Alertmanager
# ------------------------
alertmanager:
  enabled: true
  
  rbac:
    create: true

  alertmanagerSpec:
    replicas: 1
    
  config:
    global:
      resolve_timeout: 5m

# ------------------------
# Grafana
# ------------------------
grafana:
  enabled: true

  rbac:
    create: false

  adminPassword: admin
  defaultDashboardsEnabled: true

# ------------------------
# Node exporter
# ------------------------
nodeExporter:
  enabled: true

  rbac:
    create: false

# ------------------------
# kube-state-metrics
# ------------------------
kubeStateMetrics:
  enabled: true

  rbac:
    create: false
